#
# Makefile for freebsd-systems.
# This makefile was build automatically with perl-script "bm.pl".
# There might be other makefiles available for different systems.
#

CC = gcc
OBJS = src/main.o src/oaudiomanager.o src/oentity.o src/oentitymanager.o src/oerror.o src/oevent.o src/ofile.o src/ogame.o src/oglapi.o src/olevel.o src/oluacapi.o src/omap.o src/omeshmanager.o src/omessagestack.o src/omission.o src/omissionmanager.o src/omusicmanager.o src/opngtotexture.o src/optrmap.o src/optrvector.o src/oscriptmanager.o src/osettings.o src/osoundmanager.o src/ostate.o src/ostring.o src/otextmanager.o src/otexturemanager.o src/ovector.o src/ovector3.o src/oversion.o src/posix/odir.o src/posix/otimer.o src/posix/freebsd/oexedirname.o 
LUAIPATH = /usr/local/include/lua51
LUALPATH = /usr/local/lib/lua51
CFLAGS  = -g -Wall -ansi -pedantic `sdl-config --cflags` `libpng-config --cflags` -I $(LUAIPATH)
LFLAGS = `sdl-config --libs` -lSDL_mixer `libpng-config --ldflags` -lGL -lGLU -L $(LUALPATH) -llua

crates: $(OBJS)
	$(CC) -o crates $(OBJS) $(LFLAGS)

main.o: src/main.c src/odir.h src/otypes.h src/ogame.h \
  /usr/local/include/SDL/SDL.h /usr/local/include/SDL/SDL_main.h \
  /usr/local/include/SDL/SDL_stdinc.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/iconv.h \
  /usr/local/include/SDL/begin_code.h /usr/local/include/SDL/close_code.h \
  /usr/local/include/SDL/SDL_audio.h /usr/local/include/SDL/SDL_error.h \
  /usr/local/include/SDL/SDL_endian.h /usr/local/include/SDL/SDL_mutex.h \
  /usr/local/include/SDL/SDL_thread.h /usr/local/include/SDL/SDL_rwops.h \
  /usr/local/include/SDL/SDL_cdrom.h /usr/local/include/SDL/SDL_cpuinfo.h \
  /usr/local/include/SDL/SDL_events.h /usr/local/include/SDL/SDL_active.h \
  /usr/local/include/SDL/SDL_keyboard.h \
  /usr/local/include/SDL/SDL_keysym.h /usr/local/include/SDL/SDL_mouse.h \
  /usr/local/include/SDL/SDL_video.h \
  /usr/local/include/SDL/SDL_joystick.h /usr/local/include/SDL/SDL_quit.h \
  /usr/local/include/SDL/SDL_loadso.h /usr/local/include/SDL/SDL_timer.h \
  /usr/local/include/SDL/SDL_version.h src/oentity.h src/ovector3.h \
  src/oscriptmanager.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/optrvector.h src/ostring.h src/ovector.h src/oevent.h \
  /usr/local/include/SDL/SDL_opengl.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/oerror.h \
  src/otimer.h src/ostate.h src/omessagestack.h src/otextmanager.h \
  src/otexturemanager.h src/omap.h src/omeshmanager.h \
  src/omissionmanager.h src/omission.h src/olevel.h src/osettings.h \
  src/oaudiomanager.h src/osoundmanager.h src/optrmap.h \
  /usr/local/include/SDL/SDL_mixer.h /usr/local/include/SDL/SDL_types.h \
  src/omusicmanager.h src/oentitymanager.h src/oversion.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

oaudiomanager.o: src/oaudiomanager.c src/oaudiomanager.h \
  src/osoundmanager.h src/osettings.h src/oscriptmanager.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/luaconf.h \
  /usr/local/include/lua51/lauxlib.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/lualib.h src/otypes.h src/optrvector.h \
  src/ostring.h src/ovector.h src/optrmap.h \
  /usr/local/include/SDL/SDL_mixer.h /usr/local/include/SDL/SDL_types.h \
  /usr/local/include/SDL/SDL_stdinc.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/iconv.h \
  /usr/local/include/SDL/begin_code.h /usr/local/include/SDL/close_code.h \
  /usr/local/include/SDL/SDL_rwops.h /usr/local/include/SDL/SDL_error.h \
  /usr/local/include/SDL/SDL_audio.h /usr/local/include/SDL/SDL_endian.h \
  /usr/local/include/SDL/SDL_mutex.h /usr/local/include/SDL/SDL_thread.h \
  /usr/local/include/SDL/SDL_version.h src/omusicmanager.h src/oerror.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

oentity.o: src/oentity.c src/obits.h src/oentity.h src/ovector3.h \
  src/otypes.h src/oscriptmanager.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/optrvector.h src/ostring.h src/ovector.h src/oevent.h \
  /usr/local/include/SDL/SDL_opengl.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/oerror.h \
  src/odir.h src/ostate.h src/omessagestack.h src/otextmanager.h \
  src/otexturemanager.h src/omap.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

oentitymanager.o: src/oentitymanager.c src/oentitymanager.h src/oentity.h \
  src/ovector3.h src/otypes.h src/oscriptmanager.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/luaconf.h \
  /usr/local/include/lua51/lauxlib.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/lualib.h src/optrvector.h src/ostring.h \
  src/ovector.h src/oevent.h /usr/local/include/SDL/SDL_opengl.h \
  /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/optrmap.h \
  src/oerror.h src/odir.h src/ofile.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

oerror.o: src/oerror.c src/oerror.h src/otypes.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

oevent.o: src/oevent.c src/oevent.h src/otypes.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

ofile.o: src/ofile.c src/ofile.h src/otypes.h src/ostring.h src/ovector.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

ogame.o: src/ogame.c src/ogame.h /usr/local/include/SDL/SDL.h \
  /usr/local/include/SDL/SDL_main.h /usr/local/include/SDL/SDL_stdinc.h \
  /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/iconv.h \
  /usr/local/include/SDL/begin_code.h /usr/local/include/SDL/close_code.h \
  /usr/local/include/SDL/SDL_audio.h /usr/local/include/SDL/SDL_error.h \
  /usr/local/include/SDL/SDL_endian.h /usr/local/include/SDL/SDL_mutex.h \
  /usr/local/include/SDL/SDL_thread.h /usr/local/include/SDL/SDL_rwops.h \
  /usr/local/include/SDL/SDL_cdrom.h /usr/local/include/SDL/SDL_cpuinfo.h \
  /usr/local/include/SDL/SDL_events.h /usr/local/include/SDL/SDL_active.h \
  /usr/local/include/SDL/SDL_keyboard.h \
  /usr/local/include/SDL/SDL_keysym.h /usr/local/include/SDL/SDL_mouse.h \
  /usr/local/include/SDL/SDL_video.h \
  /usr/local/include/SDL/SDL_joystick.h /usr/local/include/SDL/SDL_quit.h \
  /usr/local/include/SDL/SDL_loadso.h /usr/local/include/SDL/SDL_timer.h \
  /usr/local/include/SDL/SDL_version.h src/oentity.h src/ovector3.h \
  src/otypes.h src/oscriptmanager.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/optrvector.h src/ostring.h src/ovector.h src/oevent.h \
  /usr/local/include/SDL/SDL_opengl.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/oerror.h \
  src/otimer.h src/ostate.h src/omessagestack.h src/otextmanager.h \
  src/otexturemanager.h src/omap.h src/omeshmanager.h \
  src/omissionmanager.h src/omission.h src/olevel.h src/osettings.h \
  src/oaudiomanager.h src/osoundmanager.h src/optrmap.h \
  /usr/local/include/SDL/SDL_mixer.h /usr/local/include/SDL/SDL_types.h \
  src/omusicmanager.h src/oentitymanager.h src/odir.h src/oluacapi.h \
  src/oglapi.h src/oversion.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

oglapi.o: src/oglapi.c src/oglapi.h src/ogame.h \
  /usr/local/include/SDL/SDL.h /usr/local/include/SDL/SDL_main.h \
  /usr/local/include/SDL/SDL_stdinc.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/iconv.h \
  /usr/local/include/SDL/begin_code.h /usr/local/include/SDL/close_code.h \
  /usr/local/include/SDL/SDL_audio.h /usr/local/include/SDL/SDL_error.h \
  /usr/local/include/SDL/SDL_endian.h /usr/local/include/SDL/SDL_mutex.h \
  /usr/local/include/SDL/SDL_thread.h /usr/local/include/SDL/SDL_rwops.h \
  /usr/local/include/SDL/SDL_cdrom.h /usr/local/include/SDL/SDL_cpuinfo.h \
  /usr/local/include/SDL/SDL_events.h /usr/local/include/SDL/SDL_active.h \
  /usr/local/include/SDL/SDL_keyboard.h \
  /usr/local/include/SDL/SDL_keysym.h /usr/local/include/SDL/SDL_mouse.h \
  /usr/local/include/SDL/SDL_video.h \
  /usr/local/include/SDL/SDL_joystick.h /usr/local/include/SDL/SDL_quit.h \
  /usr/local/include/SDL/SDL_loadso.h /usr/local/include/SDL/SDL_timer.h \
  /usr/local/include/SDL/SDL_version.h src/oentity.h src/ovector3.h \
  src/otypes.h src/oscriptmanager.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/optrvector.h src/ostring.h src/ovector.h src/oevent.h \
  /usr/local/include/SDL/SDL_opengl.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/oerror.h \
  src/otimer.h src/ostate.h src/omessagestack.h src/otextmanager.h \
  src/otexturemanager.h src/omap.h src/omeshmanager.h \
  src/omissionmanager.h src/omission.h src/olevel.h src/osettings.h \
  src/oaudiomanager.h src/osoundmanager.h src/optrmap.h \
  /usr/local/include/SDL/SDL_mixer.h /usr/local/include/SDL/SDL_types.h \
  src/omusicmanager.h src/oentitymanager.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

olevel.o: src/olevel.c src/olevel.h src/optrvector.h src/otypes.h \
  src/ostring.h src/ovector.h src/oerror.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

oluacapi.o: src/oluacapi.c src/oluacapi.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h src/ogame.h \
  /usr/local/include/SDL/SDL.h /usr/local/include/SDL/SDL_main.h \
  /usr/local/include/SDL/SDL_stdinc.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/iconv.h \
  /usr/local/include/SDL/begin_code.h /usr/local/include/SDL/close_code.h \
  /usr/local/include/SDL/SDL_audio.h /usr/local/include/SDL/SDL_error.h \
  /usr/local/include/SDL/SDL_endian.h /usr/local/include/SDL/SDL_mutex.h \
  /usr/local/include/SDL/SDL_thread.h /usr/local/include/SDL/SDL_rwops.h \
  /usr/local/include/SDL/SDL_cdrom.h /usr/local/include/SDL/SDL_cpuinfo.h \
  /usr/local/include/SDL/SDL_events.h /usr/local/include/SDL/SDL_active.h \
  /usr/local/include/SDL/SDL_keyboard.h \
  /usr/local/include/SDL/SDL_keysym.h /usr/local/include/SDL/SDL_mouse.h \
  /usr/local/include/SDL/SDL_video.h \
  /usr/local/include/SDL/SDL_joystick.h /usr/local/include/SDL/SDL_quit.h \
  /usr/local/include/SDL/SDL_loadso.h /usr/local/include/SDL/SDL_timer.h \
  /usr/local/include/SDL/SDL_version.h src/oentity.h src/ovector3.h \
  src/otypes.h src/oscriptmanager.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/optrvector.h src/ostring.h src/ovector.h src/oevent.h \
  /usr/local/include/SDL/SDL_opengl.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/oerror.h \
  src/otimer.h src/ostate.h src/omessagestack.h src/otextmanager.h \
  src/otexturemanager.h src/omap.h src/omeshmanager.h \
  src/omissionmanager.h src/omission.h src/olevel.h src/osettings.h \
  src/oaudiomanager.h src/osoundmanager.h src/optrmap.h \
  /usr/local/include/SDL/SDL_mixer.h /usr/local/include/SDL/SDL_types.h \
  src/omusicmanager.h src/oentitymanager.h src/odir.h src/oglapi.h \
  src/oversion.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

omap.o: src/omap.c src/omap.h src/otypes.h src/optrvector.h src/ovector.h \
  src/oerror.h src/ostring.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

omeshmanager.o: src/omeshmanager.c src/omeshmanager.h \
  src/oscriptmanager.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/otypes.h src/optrvector.h src/ostring.h src/ovector.h src/omap.h \
  /usr/local/include/SDL/SDL_opengl.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/odir.h \
  src/oerror.h /usr/local/include/SDL/SDL.h \
  /usr/local/include/SDL/SDL_main.h /usr/local/include/SDL/SDL_stdinc.h \
  /usr/local/include/iconv.h /usr/local/include/SDL/begin_code.h \
  /usr/local/include/SDL/close_code.h /usr/local/include/SDL/SDL_audio.h \
  /usr/local/include/SDL/SDL_error.h /usr/local/include/SDL/SDL_endian.h \
  /usr/local/include/SDL/SDL_mutex.h /usr/local/include/SDL/SDL_thread.h \
  /usr/local/include/SDL/SDL_rwops.h /usr/local/include/SDL/SDL_cdrom.h \
  /usr/local/include/SDL/SDL_cpuinfo.h \
  /usr/local/include/SDL/SDL_events.h /usr/local/include/SDL/SDL_active.h \
  /usr/local/include/SDL/SDL_keyboard.h \
  /usr/local/include/SDL/SDL_keysym.h /usr/local/include/SDL/SDL_mouse.h \
  /usr/local/include/SDL/SDL_video.h \
  /usr/local/include/SDL/SDL_joystick.h /usr/local/include/SDL/SDL_quit.h \
  /usr/local/include/SDL/SDL_loadso.h /usr/local/include/SDL/SDL_timer.h \
  /usr/local/include/SDL/SDL_version.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

omessagestack.o: src/omessagestack.c src/omessagestack.h \
  src/otextmanager.h src/ostring.h src/otypes.h src/ovector.h \
  src/otexturemanager.h src/omap.h src/optrvector.h \
  /usr/local/include/SDL/SDL_opengl.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/oerror.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

omission.o: src/omission.c src/omission.h src/olevel.h src/optrvector.h \
  src/otypes.h src/ostring.h src/ovector.h src/oerror.h src/ofile.h \
  src/ogame.h /usr/local/include/SDL/SDL.h \
  /usr/local/include/SDL/SDL_main.h /usr/local/include/SDL/SDL_stdinc.h \
  /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/iconv.h \
  /usr/local/include/SDL/begin_code.h /usr/local/include/SDL/close_code.h \
  /usr/local/include/SDL/SDL_audio.h /usr/local/include/SDL/SDL_error.h \
  /usr/local/include/SDL/SDL_endian.h /usr/local/include/SDL/SDL_mutex.h \
  /usr/local/include/SDL/SDL_thread.h /usr/local/include/SDL/SDL_rwops.h \
  /usr/local/include/SDL/SDL_cdrom.h /usr/local/include/SDL/SDL_cpuinfo.h \
  /usr/local/include/SDL/SDL_events.h /usr/local/include/SDL/SDL_active.h \
  /usr/local/include/SDL/SDL_keyboard.h \
  /usr/local/include/SDL/SDL_keysym.h /usr/local/include/SDL/SDL_mouse.h \
  /usr/local/include/SDL/SDL_video.h \
  /usr/local/include/SDL/SDL_joystick.h /usr/local/include/SDL/SDL_quit.h \
  /usr/local/include/SDL/SDL_loadso.h /usr/local/include/SDL/SDL_timer.h \
  /usr/local/include/SDL/SDL_version.h src/oentity.h src/ovector3.h \
  src/oscriptmanager.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/oevent.h /usr/local/include/SDL/SDL_opengl.h \
  /usr/local/include/GL/gl.h /usr/local/include/GL/glext.h \
  /usr/local/include/GL/glu.h src/otimer.h src/ostate.h \
  src/omessagestack.h src/otextmanager.h src/otexturemanager.h src/omap.h \
  src/omeshmanager.h src/omissionmanager.h src/osettings.h \
  src/oaudiomanager.h src/osoundmanager.h src/optrmap.h \
  /usr/local/include/SDL/SDL_mixer.h /usr/local/include/SDL/SDL_types.h \
  src/omusicmanager.h src/oentitymanager.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

omissionmanager.o: src/omissionmanager.c src/omissionmanager.h \
  src/omission.h src/olevel.h src/optrvector.h src/otypes.h src/ostring.h \
  src/ovector.h src/oerror.h src/odir.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

omusicmanager.o: src/omusicmanager.c src/omusicmanager.h src/osettings.h \
  src/oscriptmanager.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/otypes.h src/optrvector.h src/ostring.h src/ovector.h src/optrmap.h \
  /usr/local/include/SDL/SDL_mixer.h /usr/local/include/SDL/SDL_types.h \
  /usr/local/include/SDL/SDL_stdinc.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/iconv.h \
  /usr/local/include/SDL/begin_code.h /usr/local/include/SDL/close_code.h \
  /usr/local/include/SDL/SDL_rwops.h /usr/local/include/SDL/SDL_error.h \
  /usr/local/include/SDL/SDL_audio.h /usr/local/include/SDL/SDL_endian.h \
  /usr/local/include/SDL/SDL_mutex.h /usr/local/include/SDL/SDL_thread.h \
  /usr/local/include/SDL/SDL_version.h src/odir.h src/oerror.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

opngtotexture.o: src/opngtotexture.c src/opngtotexture.h src/otypes.h \
  /usr/local/include/SDL/SDL_opengl.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/oerror.h \
  /usr/local/include/png.h /usr/local/include/pngconf.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

optrmap.o: src/optrmap.c src/optrmap.h src/otypes.h src/optrvector.h \
  src/oerror.h src/ostring.h src/ovector.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

optrvector.o: src/optrvector.c src/optrvector.h src/otypes.h src/oerror.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

oscriptmanager.o: src/oscriptmanager.c src/oscriptmanager.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/luaconf.h \
  /usr/local/include/lua51/lauxlib.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/lualib.h src/otypes.h src/optrvector.h \
  src/oerror.h src/ostring.h src/ovector.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

osettings.o: src/osettings.c src/osettings.h src/oscriptmanager.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/luaconf.h \
  /usr/local/include/lua51/lauxlib.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/lualib.h src/otypes.h src/optrvector.h \
  src/oerror.h src/odir.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

osoundmanager.o: src/osoundmanager.c src/osoundmanager.h src/osettings.h \
  src/oscriptmanager.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/otypes.h src/optrvector.h src/ostring.h src/ovector.h src/optrmap.h \
  /usr/local/include/SDL/SDL_mixer.h /usr/local/include/SDL/SDL_types.h \
  /usr/local/include/SDL/SDL_stdinc.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/iconv.h \
  /usr/local/include/SDL/begin_code.h /usr/local/include/SDL/close_code.h \
  /usr/local/include/SDL/SDL_rwops.h /usr/local/include/SDL/SDL_error.h \
  /usr/local/include/SDL/SDL_audio.h /usr/local/include/SDL/SDL_endian.h \
  /usr/local/include/SDL/SDL_mutex.h /usr/local/include/SDL/SDL_thread.h \
  /usr/local/include/SDL/SDL_version.h src/odir.h src/oerror.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

ostate.o: src/ostate.c src/ostate.h src/oentity.h src/ovector3.h \
  src/otypes.h src/oscriptmanager.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/optrvector.h src/ostring.h src/ovector.h src/oevent.h \
  /usr/local/include/SDL/SDL_opengl.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h \
  src/omessagestack.h src/otextmanager.h src/otexturemanager.h src/omap.h \
  src/oerror.h src/odir.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

ostring.o: src/ostring.c src/ostring.h src/otypes.h src/ovector.h \
  src/oerror.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

otextmanager.o: src/otextmanager.c src/otextmanager.h src/ostring.h \
  src/otypes.h src/ovector.h src/otexturemanager.h src/omap.h \
  src/optrvector.h /usr/local/include/SDL/SDL_opengl.h \
  /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/oglapi.h \
  src/ogame.h /usr/local/include/SDL/SDL.h \
  /usr/local/include/SDL/SDL_main.h /usr/local/include/SDL/SDL_stdinc.h \
  /usr/local/include/iconv.h /usr/local/include/SDL/begin_code.h \
  /usr/local/include/SDL/close_code.h /usr/local/include/SDL/SDL_audio.h \
  /usr/local/include/SDL/SDL_error.h /usr/local/include/SDL/SDL_endian.h \
  /usr/local/include/SDL/SDL_mutex.h /usr/local/include/SDL/SDL_thread.h \
  /usr/local/include/SDL/SDL_rwops.h /usr/local/include/SDL/SDL_cdrom.h \
  /usr/local/include/SDL/SDL_cpuinfo.h \
  /usr/local/include/SDL/SDL_events.h /usr/local/include/SDL/SDL_active.h \
  /usr/local/include/SDL/SDL_keyboard.h \
  /usr/local/include/SDL/SDL_keysym.h /usr/local/include/SDL/SDL_mouse.h \
  /usr/local/include/SDL/SDL_video.h \
  /usr/local/include/SDL/SDL_joystick.h /usr/local/include/SDL/SDL_quit.h \
  /usr/local/include/SDL/SDL_loadso.h /usr/local/include/SDL/SDL_timer.h \
  /usr/local/include/SDL/SDL_version.h src/oentity.h src/ovector3.h \
  src/oscriptmanager.h /usr/local/include/lua51/lua.h \
  /usr/local/include/lua51/luaconf.h /usr/local/include/lua51/lauxlib.h \
  /usr/local/include/lua51/lua.h /usr/local/include/lua51/lualib.h \
  src/oevent.h src/oerror.h src/otimer.h src/ostate.h src/omessagestack.h \
  src/omeshmanager.h src/omissionmanager.h src/omission.h src/olevel.h \
  src/osettings.h src/oaudiomanager.h src/osoundmanager.h src/optrmap.h \
  /usr/local/include/SDL/SDL_mixer.h /usr/local/include/SDL/SDL_types.h \
  src/omusicmanager.h src/oentitymanager.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

otexturemanager.o: src/otexturemanager.c src/otexturemanager.h \
  src/otypes.h src/ostring.h src/ovector.h src/omap.h src/optrvector.h \
  /usr/local/include/SDL/SDL_opengl.h /usr/local/include/SDL/SDL_config.h \
  /usr/local/include/SDL/SDL_platform.h /usr/local/include/GL/gl.h \
  /usr/local/include/GL/glext.h /usr/local/include/GL/glu.h src/odir.h \
  src/oerror.h src/opngtotexture.h /usr/local/include/SDL/SDL.h \
  /usr/local/include/SDL/SDL_main.h /usr/local/include/SDL/SDL_stdinc.h \
  /usr/local/include/iconv.h /usr/local/include/SDL/begin_code.h \
  /usr/local/include/SDL/close_code.h /usr/local/include/SDL/SDL_audio.h \
  /usr/local/include/SDL/SDL_error.h /usr/local/include/SDL/SDL_endian.h \
  /usr/local/include/SDL/SDL_mutex.h /usr/local/include/SDL/SDL_thread.h \
  /usr/local/include/SDL/SDL_rwops.h /usr/local/include/SDL/SDL_cdrom.h \
  /usr/local/include/SDL/SDL_cpuinfo.h \
  /usr/local/include/SDL/SDL_events.h /usr/local/include/SDL/SDL_active.h \
  /usr/local/include/SDL/SDL_keyboard.h \
  /usr/local/include/SDL/SDL_keysym.h /usr/local/include/SDL/SDL_mouse.h \
  /usr/local/include/SDL/SDL_video.h \
  /usr/local/include/SDL/SDL_joystick.h /usr/local/include/SDL/SDL_quit.h \
  /usr/local/include/SDL/SDL_loadso.h /usr/local/include/SDL/SDL_timer.h \
  /usr/local/include/SDL/SDL_version.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

ovector.o: src/ovector.c src/ovector.h src/otypes.h src/oerror.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

ovector3.o: src/ovector3.c src/ovector3.h src/otypes.h src/oerror.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

oversion.o: src/oversion.c src/otypes.h src/oerror.h
	$(CC) -c -o $@ $(CFLAGS) src/$<

odir.o: src/posix/odir.c src/posix/../odir.h src/posix/../otypes.h \
  src/posix/../oerror.h src/posix/../ostring.h src/posix/../ovector.h
	$(CC) -c -o $@ $(CFLAGS) $<

otimer.o: src/posix/otimer.c src/posix/../otimer.h src/posix/../otypes.h \
  src/posix/../otypes.h src/posix/../oerror.h
	$(CC) -c -o $@ $(CFLAGS) $<

oexedirname.o: src/posix/freebsd/oexedirname.c \
  src/posix/freebsd/../../odir.h src/posix/freebsd/../../otypes.h \
  src/posix/freebsd/../../oerror.h
	$(CC) -c -o $@ $(CFLAGS) $<

clean:
	rm -f src/*.o src/posix/*.o src/posix/freebsd/*.o
	rm -f crates
